apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-dns-server
  labels:
    k8s-app: kube-dns-server
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns-server
  template:
    metadata:
      labels:
        k8s-app: kube-dns-server
        name: kube-dns-server
    spec:
      hostNetwork: true
      containers:
      - image: aledbf/kube-dns-server:0.1
        name: kube-dns-server
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
